# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.runs/synth_1/CPU3_Top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.cache/wt [current_project]
set_property parent.project_path C:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files C:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.srcs/sources_1/RIUS_test.coe
add_files C:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.srcs/sources_1/ip/RIUS_data.coe
add_files C:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.srcs/sources_1/ip/RIUSJB_test.coe
add_files C:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.srcs/sources_1/ip/RIUSJB_data.coe
read_verilog -library xil_defaultlib {
  C:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.srcs/sources_1/new/ABF.v
  C:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.srcs/sources_1/new/ADD.v
  C:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.srcs/sources_1/new/ADDpc0.v
  C:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.srcs/sources_1/new/ALU.v
  C:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.srcs/sources_1/new/ALU_ABF.v
  C:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.srcs/sources_1/new/CU.v
  C:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.srcs/sources_1/new/D1.v
  C:/Users/zhangtaoyuan/FPGA/Expr1_ALU/Expr1_ALU.srcs/sources_1/new/DISP.v
  C:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.srcs/sources_1/new/DM.v
  C:/Users/zhangtaoyuan/FPGA/Expr1_ALU/Expr1_ALU.srcs/sources_1/new/Display.v
  C:/Users/zhangtaoyuan/FPGA/Expr1_ALU/Expr1_ALU.srcs/sources_1/new/Fdiv.v
  C:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.srcs/sources_1/new/ID2.v
  C:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.srcs/sources_1/new/ID2_CU.v
  C:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.srcs/sources_1/new/IM.v
  C:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.srcs/sources_1/new/IM_IF.v
  C:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.srcs/sources_1/new/IM_IF_ID.v
  C:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.srcs/sources_1/new/IR.v
  C:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.srcs/sources_1/new/ImmU.v
  C:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.srcs/sources_1/new/MDR.v
  C:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.srcs/sources_1/new/PC.v
  C:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.srcs/sources_1/new/PC0.v
  C:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.srcs/sources_1/new/RIUSJB_CPU.v
  C:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.srcs/sources_1/new/Regs.v
  C:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.srcs/sources_1/new/CPU3_Top.v
}
read_ip -quiet C:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.srcs/sources_1/ip/ROM_SP2/ROM_SP2.xci
set_property used_in_implementation false [get_files -all c:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.srcs/sources_1/ip/ROM_SP2/ROM_SP2_ooc.xdc]

read_ip -quiet C:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.srcs/sources_1/ip/RAM_SP2/RAM_SP2.xci
set_property used_in_implementation false [get_files -all c:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.srcs/sources_1/ip/RAM_SP2/RAM_SP2_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.srcs/constrs_1/new/CPU3_1.xdc
set_property used_in_implementation false [get_files C:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.srcs/constrs_1/new/CPU3_1.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top CPU3_Top -part xc7a100tcsg324-2L
OPTRACE "synth_design" END { }


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CPU3_Top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file CPU3_Top_utilization_synth.rpt -pb CPU3_Top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
