# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.srcs/sources_1/ip/RAM_SP2/RAM_SP2.xci
# IP: The module: 'RAM_SP2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.srcs/sources_1/ip/RAM_SP2/RAM_SP2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_SP2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.srcs/sources_1/ip/RAM_SP2/RAM_SP2.xci
# IP: The module: 'RAM_SP2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zhangtaoyuan/FPGA/Expr9_CPU3/Expr9_CPU3.srcs/sources_1/ip/RAM_SP2/RAM_SP2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_SP2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
