# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/zhangtaoyuan/FPGA/Expr6_Instruction/Expr6_Instruction.srcs/sources_1/ip/ROM_SP/ROM_SP.xci
# IP: The module: 'ROM_SP' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zhangtaoyuan/FPGA/Expr6_Instruction/Expr6_Instruction.srcs/sources_1/ip/ROM_SP/ROM_SP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_SP'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/zhangtaoyuan/FPGA/Expr6_Instruction/Expr6_Instruction.srcs/sources_1/ip/ROM_SP/ROM_SP.xci
# IP: The module: 'ROM_SP' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zhangtaoyuan/FPGA/Expr6_Instruction/Expr6_Instruction.srcs/sources_1/ip/ROM_SP/ROM_SP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_SP'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
